import { Event, Fan, Message, Player, Team } from '@/types';

export const MOCK_TEAMS: Team[] = [
  {
    id: '1',
    name: 'Varsity Knights',
    record: '12-3',
    playerCount: 15,
    avgPPG: 78.2,
  },
  {
    id: '2',
    name: 'JV Eagles',
    record: '8-5',
    playerCount: 12,
    avgPPG: 65.4,
  },
];

export const MOCK_PLAYERS: Player[] = [
  {
    id: '1',
    name: 'Marcus Johnson',
    jerseyNumber: '23',
    teamId: '1',
    stats: { gamesPlayed: 15, points: 20.7, assists: 5.2, rebounds: 8.1, offensiveRebounds: 2.5, defensiveRebounds: 5.6, steals: 2.3, blocks: 1.1, turnovers: 2.5, fouls: 2.8, fieldGoalsMade: 0, fieldGoalsAttempted: 0, threePointersMade: 0, threePointersAttempted: 0, freeThrowsMade: 0, freeThrowsAttempted: 0 },
  },
  {
    id: '2',
    name: 'Tyler Rodriguez',
    jerseyNumber: '15',
    teamId: '1',
    stats: { gamesPlayed: 15, points: 18.3, assists: 3.8, rebounds: 4.4, offensiveRebounds: 1.2, defensiveRebounds: 3.2, steals: 1.9, blocks: 0.6, turnovers: 1.8, fouls: 2.2, fieldGoalsMade: 0, fieldGoalsAttempted: 0, threePointersMade: 0, threePointersAttempted: 0, freeThrowsMade: 0, freeThrowsAttempted: 0 },
  },
  {
    id: '3',
    name: 'Jayden Williams',
    jerseyNumber: '10',
    teamId: '1',
    stats: { gamesPlayed: 15, points: 15.6, assists: 7.2, rebounds: 3.5, offensiveRebounds: 0.8, defensiveRebounds: 2.7, steals: 2.1, blocks: 0.3, turnovers: 2.9, fouls: 2.5, fieldGoalsMade: 0, fieldGoalsAttempted: 0, threePointersMade: 0, threePointersAttempted: 0, freeThrowsMade: 0, freeThrowsAttempted: 0 },
  },
  {
    id: '4',
    name: 'Brandon Lee',
    jerseyNumber: '32',
    teamId: '1',
    stats: { gamesPlayed: 15, points: 13.0, assists: 2.1, rebounds: 9.8, offensiveRebounds: 3.2, defensiveRebounds: 6.6, steals: 1.2, blocks: 2.4, turnovers: 1.5, fouls: 3.2, fieldGoalsMade: 0, fieldGoalsAttempted: 0, threePointersMade: 0, threePointersAttempted: 0, freeThrowsMade: 0, freeThrowsAttempted: 0 },
  },
  {
    id: '5',
    name: 'Chris Thompson',
    jerseyNumber: '11',
    teamId: '1',
    stats: { gamesPlayed: 15, points: 13.4, assists: 2.8, rebounds: 5.3, offensiveRebounds: 1.5, defensiveRebounds: 3.8, steals: 1.6, blocks: 0.8, turnovers: 1.2, fouls: 2.1, fieldGoalsMade: 0, fieldGoalsAttempted: 0, threePointersMade: 0, threePointersAttempted: 0, freeThrowsMade: 0, freeThrowsAttempted: 0 },
  },
  {
    id: '6',
    name: 'Jordan Davis',
    jerseyNumber: '7',
    teamId: '2',
    stats: { gamesPlayed: 13, points: 15.2, assists: 4.1, rebounds: 6.2, offensiveRebounds: 1.8, defensiveRebounds: 4.4, steals: 1.8, blocks: 0.9, turnovers: 2.0, fouls: 2.4, fieldGoalsMade: 0, fieldGoalsAttempted: 0, threePointersMade: 0, threePointersAttempted: 0, freeThrowsMade: 0, freeThrowsAttempted: 0 },
  },
  {
    id: '7',
    name: 'Kyle Anderson',
    jerseyNumber: '12',
    teamId: '2',
    stats: { gamesPlayed: 13, points: 12.8, assists: 3.2, rebounds: 5.5, offensiveRebounds: 1.4, defensiveRebounds: 4.1, steals: 1.3, blocks: 0.5, turnovers: 1.7, fouls: 2.0, fieldGoalsMade: 0, fieldGoalsAttempted: 0, threePointersMade: 0, threePointersAttempted: 0, freeThrowsMade: 0, freeThrowsAttempted: 0 },
  },
];

export const MOCK_EVENTS: Event[] = [
  {
    id: '1',
    type: 'game',
    title: 'vs Lincoln High',
    opponent: 'Lincoln High',
    teamId: '1',
    teamName: 'Varsity Knights',
    date: '2025-11-04',
    time: '18:00',
    location: 'Home Court',
    isHome: true,
  },
  {
    id: '2',
    type: 'practice',
    title: 'Team Practice',
    teamId: '1',
    teamName: 'Varsity Knights',
    date: '2025-11-03',
    time: '16:00',
    location: 'Gym A',
  },
  {
    id: '3',
    type: 'practice',
    title: 'Morning Shootaround',
    teamId: '1',
    teamName: 'Varsity Knights',
    date: '2025-11-02',
    time: '08:00',
    location: 'Gym A',
  },
  {
    id: '4',
    type: 'game',
    title: 'vs Roosevelt',
    opponent: 'Roosevelt',
    teamId: '2',
    teamName: 'JV Eagles',
    date: '2025-11-02',
    time: '15:30',
    location: 'Away',
    isHome: false,
  },
  {
    id: '5',
    type: 'practice',
    title: 'Team Practice',
    teamId: '1',
    teamName: 'Varsity Knights',
    date: '2025-11-02',
    time: '17:00',
    location: 'Home Court',
  },
];

export const MOCK_FANS: Fan[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@email.com',
    teamId: '1',
    playerId: '1',
    playerName: 'Marcus Johnson',
    status: 'active',
    invitedAt: '2025-10-15',
    joinedAt: '2025-10-15',
  },
  {
    id: '2',
    name: 'Michael Rodriguez',
    email: 'michael.rodriguez@email.com',
    teamId: '1',
    playerId: '2',
    playerName: 'Tyler Rodriguez',
    status: 'active',
    invitedAt: '2025-10-16',
    joinedAt: '2025-10-17',
  },
  {
    id: '3',
    name: 'Lisa Williams',
    email: 'lisa.williams@email.com',
    teamId: '1',
    playerId: '3',
    playerName: 'Jayden Williams',
    status: 'invited',
    invitedAt: '2025-11-01',
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: '1',
    threadId: '1',
    threadName: 'Varsity Knights',
    lastMessage: 'Great practice today team!',
    timestamp: '10:30 AM',
    unreadCount: 2,
    avatar: 'Va',
  },
  {
    id: '2',
    threadId: '2',
    threadName: 'Coach Thompson',
    lastMessage: 'Can you stay after practice?',
    timestamp: '9:15 AM',
    unreadCount: 0,
    avatar: 'Co',
  },
  {
    id: '3',
    threadId: '3',
    threadName: 'Parents Group',
    lastMessage: 'Game time changed to 6pm',
    timestamp: '4:45 PM',
    unreadCount: 0,
    avatar: 'Pa',
  },
];
